@BASE_URL=http://localhost:3000
### EXAMPLE
GET {{BASE_URL}}/


### REGISTER
POST {{BASE_URL}}/api/auth/register
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "nim": "12345",
  "password": "test",
  "username": "test",
  "fullname": "test"
}
{{
      REFRESH_TOKEN = response.parsedBody.data?.token
      ACCESS_TOKEN = response.parsedBody.data?.token
}}

### LOGIN
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
 "identifier": "12345",
 "password": "test"
}
{{
    REFRESH_TOKEN = response.parsedBody.data?.rt
    ACCESS_TOKEN = response.parsedBody.data?.at
}}

### REFRESH
GET {{BASE_URL}}/api/auth/refresh
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{REFRESH_TOKEN}}

{{
    REFRESH_TOKEN = response.parsedBody.data?.rt
    ACCESS_TOKEN = response.parsedBody.data?.at
}}

### LOGOUT
DELETE {{BASE_URL}}/api/auth
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{ACCESS_TOKEN}}
