---
openapi: 3.0.0
info:
  title: CLIC API
  description: CLIC API Spec
  version: 1.0.0
tags:
  - name: Auth
    description: Authentication endpoints
servers:
  - url: http://localhost:3000
paths:
  '/api/auth/register':
    post:
      summary: Register User
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nim:
                  type: string
                username:
                  type: string
                password:
                  type: string
                fullname:
                  type: string
              required:
                - nim
                - password
                - fullname
      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      at:
                        type: string
                      rt:
                        type: string
        '400':
          description: Validation or existence error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items: {}
  '/api/auth/login':
    post:
      summary: Login User
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                password:
                  type: string
              required:
                - identifier
                - password
      responses:
        '200':
          description: Login successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      at:
                        type: string
                      rt:
                        type: string
        '400':
          description: Validation error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: string
        '401':
          description: Credential invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                  message:
                    type: string
        '404':
          description: Credential not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                  message:
                    type: string
  '/api/auth/refresh':
    get:
      summary: Refresh User Access Token
      tags:
        - Auth
      parameters:
        - in: header
          name: Authorization
          description:
            Refresh token to get/renew access token for authenticated user,
            available for 7 days
          required: true
          schema:
            type: string
            required:
              - Authorization
            example: Bearer JWTREFRESHTOKEN
      responses:
        '200':
          description: Token refreshed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      at:
                        type: string
                      rt:
                        type: string
        '401':
          description: Invalid credential.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                  message:
                    type: string
  '/api/auth':
    delete:
      summary: Logout User
      tags:
        - Auth
      parameters:
        - in: header
          name: Authorization
          description:
            Access token to get/renew access token for authenticated user,
            available for 7 days
          required: true
          schema:
            type: string
            required:
              - Authorization
            example: Bearer JWTACCESSTOKEN
      responses:
        '200':
          description: Logout successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: boolean
        '401':
          description: Invalid credential.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                  message:
                    type: string
